### ISSUE TITLE
Bug: changing of image does not work.

### ISSUE THREAD

**Issue by darewealth** [fossasia/open-event-organizer-android#1803] opened 2019-07-10 08:14 UTC
**Describe the bug**
When I uploaded an image on the profile, it works, but when I tried to change the image to another image, the image on the profile refused to change. 

**To Reproduce**

1. Launch the app
2. Click on the menu 
3. Click on the profile picture click the picture again
4. Then select any picture of your choice 
5. See error.

**Expected behavior**
I expect that I should be able to change the image anytime I want.

**Screenshots**
https://youtu.be/ONQm8IpDMds

**Smartphone Info:**

* App Version: 1.3.0 
* Android Version:7.0
* Device: Gionee X1

**Comment by ShridharGoel** [comment] 2019-07-11 09:38
Are you using the debug version or the release version of the app?

**Comment by ShridharGoel** [comment] 2019-07-13 16:30
Closing it since it's a server side issue: https://github.com/fossasia/open-event-server/issues/6174
Can be reopened if needed.

**Comment by iamareebjamal** [comment] 2019-07-13 19:20
Will be closed once it is resolved upstream

**Comment by darewealth** [comment] 2019-07-14 17:16
@ShridharGoel  I am using the release version of the app?

**Comment by ShridharGoel** [comment] 2019-07-17 20:15
@darewealth Not able to reproduce this issue in the release version.

![Profile image change](https://user-images.githubusercontent.com/35566748/61408432-a03c2800-a8fd-11e9-99f0-6782ab3ed78d.gif)

**Comment by codesurf** [comment] 2020-08-24 10:39
Is this issue still open?

**Comment by Shhreyya** [comment] 2020-12-20 17:39
@ShridharGoel can I work on this issue?

**Closed** 2023-04-29 12:23 UTC
Labels: bug
