### ISSUE TITLE
Profile image deleted not working fine and navigation header data is not updated after changes.

### ISSUE THREAD

**Issue by TarunPal3551** [fossasia/open-event-organizer-android#1977] opened 2019-11-18 18:49 UTC
**Describe the bug**
The profile image is not deleted and Profile image view is not updated at Navigation Header 

**To Reproduce**
1. Go to 'Navigation Menu '
2. Click on 'Profile ImageView'
3. Upload a new image by clicking on ImageView and after uploading image''
4. Go back see the navigation header imageView, you see the bug
5. Now to go to the profile section by click on navigation header image view 
6. Click on delete icon and then Refresh the profile section
7. You see the bug

**Expected behavior**
The profile must be deleted and the navigation header should be updated after deletion and uploading of Profile Image.

**Screenshots**
![20191118-232721-480x960 (1)](https://user-images.githubusercontent.com/33154835/69079871-f0202c80-0a60-11ea-9e5b-3e9d7d947c0d.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [Asus M1 PRO]|
|Android Version| [Pie 9.0]   |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by njnaman** [comment] 2019-11-25 18:47
can i take this?

**Comment by njnaman** [comment] 2019-11-28 09:23
@liveHarshit can i take this?

**Comment by liveHarshit** [comment] 2019-11-28 09:27
Go ahead

**Comment by rishabh-997** [comment] 2019-12-03 09:32
@liveHarshit sir, I checked the log messages, the problem is on the server-side, the profile URL is not getting updated as the same URL is being received as before. It is not set to null...

**Comment by ShridharGoel** [comment] 2019-12-03 09:35
Duplicate of #1859 and #1860 

Server side issue: https://github.com/fossasia/open-event-server/issues/6303

**Closed by ShridharGoel** 2019-12-03 09:35 UTC
Labels: bug
